[package]
name = "masterror-derive"
version = "0.1.0"
edition = "2024"
rust-version = "1.89"
description = "Derive macro for masterror"
license = "MIT OR Apache-2.0"
authors = ["masterror maintainers"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full", "extra-traits"] }
