# SPDX-FileCopyrightText: 2025 RAprogramm <andrey.rozanov.vl@gmail.com>
#
# SPDX-License-Identifier: MIT

# Codecov configuration for masterror project
# Documentation: https://docs.codecov.com/docs/codecov-yaml

codecov:
  # Default branch for coverage comparison
  branch: main
  # Always use YAML from main branch
  strict_yaml_branch: main
  # Maximum age of report before expiration
  max_report_age: 12h
  # Require CI to pass before processing coverage
  require_ci_to_pass: true

coverage:
  # Precision for coverage percentage (0-5 decimal places)
  precision: 2
  # Round coverage to nearest value
  round: down
  # Coverage range (red to green)
  range: 90..100

  status:
    # Project-level coverage status check
    project:
      default:
        # Target coverage percentage (auto = maintain current level)
        target: 95%
        # Allow coverage to drop by max 1% before failing
        threshold: 1%
        # Compare against base commit
        base: auto
        # Post status for all commits, not just PRs
        if_ci_failed: error
        only_pulls: false

    # Patch-level coverage status check (new code only)
    patch:
      default:
        # Target coverage for new code
        target: 95%
        # Allow some flexibility for new code
        threshold: 1%
        base: auto
        if_ci_failed: error

    # Changes status (diff between head and base)
    changes:
      default:
        base: auto
        if_ci_failed: error

  # Ignore these paths from coverage
  ignore:
    - "tests/**/*"
    - "benches/**/*"
    - "examples/**/*"
    - "**/test_*.rs"

# Pull request comment configuration
comment:
  # Layout for PR comments (Free tier compatible)
  layout: "condensed_header, condensed_files, condensed_footer"
  # Update existing comment instead of creating new ones
  behavior: default
  # Post comment even if coverage doesn't change
  require_changes: false
  # Require base report for comparison
  require_base: yes
  # Require head report to post comment
  require_head: yes
  # Show carryforward flags in comment
  show_carryforward_flags: true
  # Show project coverage in comment
  hide_project_coverage: false

# GitHub integration settings
github_checks:
  annotations: true
