# Makefile.toml for cargo-make
# Usage:
#   cargo make ci
#   TAG=v0.1.1 cargo make release
#   CARGO_REGISTRY_TOKEN=... TAG=v0.1.1 cargo make publish

[config]
default_task = "ci"

[env]
ALL_FEATURES = "true"

# ------- Core checks -------

[tasks.fmt]
clear = true
command = "cargo"
args = ["fmt", "--all", "--", "--check"]
description = "Check rustfmt formatting for the entire workspace"

[tasks.clippy]
clear = true
script = ['''
  #!/usr/bin/env bash
  set -euo pipefail
  if [ "${ALL_FEATURES}" = "true" ]; then
    cargo clippy --workspace --all-targets --all-features -- -D warnings
  else
    cargo clippy --workspace --all-targets -- -D warnings
  fi
  ''']
description = "Run clippy for all targets; fail on warnings"

[tasks.test]
clear = true
script = ['''
  #!/usr/bin/env bash
  set -euo pipefail
  if [ "${ALL_FEATURES}" = "true" ]; then
    cargo test --workspace --all-features --no-fail-fast
  else
    cargo test --workspace --no-fail-fast
  fi
  ''']
description = "Run tests (optionally with all features)"

[tasks.package]
clear = true
command = "cargo"
args = ["package", "--locked"]
description = "Verify that the crate can be packaged cleanly"

[tasks.ci]
dependencies = ["fmt", "clippy", "test", "package"]
description = "Run fmt, clippy, tests, and packaging checks"

# ------- Release gatekeeping -------

[tasks.check_tag_env]
clear = true
script = ['''
  #!/usr/bin/env bash
  set -euo pipefail
  if [ -z "${TAG:-}" ]; then
    echo "TAG env var is required, e.g. TAG=v0.1.1"
    exit 1
  fi
  ''']
description = "Ensure TAG env var is provided (e.g. TAG=v1.2.3)"

[tasks.ensure_tag_matches_version]
clear = true
script = [
  '''
  #!/usr/bin/env bash
  set -euo pipefail
  TAG="${TAG#refs/tags/}"

  if command -v jq >/dev/null 2>&1; then
    FILE_VER="$(cargo metadata --no-deps --format-version=1 | jq -r '.packages[0].version')"
  else
    FILE_VER="$(cargo metadata --no-deps --format-version=1 | sed -n 's/.*\"version\":\"\\([^\"]*\\)\".*/\\1/p' | head -n1)"
  fi

  if [ -z "${FILE_VER}" ]; then
    echo "Unable to parse version from cargo metadata."
    exit 1
  fi

  if [ "${TAG}" != "v${FILE_VER}" ]; then
    echo "Tag ${TAG} != Cargo.toml version v${FILE_VER}"
    exit 1
  fi

  echo "Tag ${TAG} matches Cargo.toml version v${FILE_VER}"
  ''',
]
dependencies = ["check_tag_env"]
description = "Ensure git tag matches Cargo.toml version"

[tasks.check_token]
clear = true
script = ['''
  #!/usr/bin/env bash
  set -euo pipefail
  if [ -z "${CARGO_REGISTRY_TOKEN:-}" ]; then
    echo "CARGO_REGISTRY_TOKEN is required to publish."
    exit 1
  fi
  ''']
description = "Ensure crates.io token is present in env"

# ------- Publish & Release -------

[tasks.publish]
clear = true
script = ['''
  #!/usr/bin/env bash
  set -euo pipefail
  cargo publish --locked --token "${CARGO_REGISTRY_TOKEN}"
  ''']
dependencies = ["check_token", "ensure_tag_matches_version", "ci"]
description = "Publish crate to crates.io after checks and tag/version verification"

[tasks.tag]
clear = true
script = [
  '''
  #!/usr/bin/env bash
  set -euo pipefail

  if command -v jq >/dev/null 2>&1; then
    VER="$(cargo metadata --no-deps --format-version=1 | jq -r '.packages[0].version')"
  else
    VER="$(cargo metadata --no-deps --format-version=1 | sed -n 's/.*\"version\":\"\\([^\"]*\\)\".*/\\1/p' | head -n1)"
  fi

  if [ -z "${VER}" ]; then
    echo "Unable to extract version from Cargo metadata."
    exit 1
  fi

  TAG="v${VER}"

  if git rev-parse "${TAG}" >/dev/null 2>&1; then
    echo "Tag ${TAG} already exists."
    exit 1
  fi

  git tag "${TAG}"
  echo "Created tag ${TAG}. You can push it with: git push origin ${TAG}"
  ''',
]
description = "Create git tag vX.Y.Z from Cargo.toml version (does not push)"

[tasks.release]
clear = true
dependencies = ["publish"]
description = "Run checks and publish the crate (requires TAG and token)"

# ------- Extras -------

[tasks.format]
clear = true
description = "Format code using rustfmt on nightly (optional)"
script_runner = "bash"
script = ['''
  set -euo pipefail
  if ! rustup toolchain list | grep -q "^nightly"; then
    echo "Installing nightly toolchain for rustfmt..."
    rustup toolchain install nightly >/dev/null
  fi
  rustup component add rustfmt --toolchain nightly >/dev/null
  cargo +nightly fmt --
''']

[tasks.install-hooks]
clear = true
workspace = false
description = "Install git pre-commit hook from .hooks/"
script_runner = "bash"
script = [
  'set -euo pipefail',
  'if [ ! -f .hooks/pre-commit ]; then echo "❌ .hooks/pre-commit не найден!"; exit 1; fi',
  'echo "🔗 Linking .hooks/pre-commit to .git/hooks/pre-commit..."',
  'mkdir -p .git/hooks',
  'ln -sf ../../.hooks/pre-commit .git/hooks/pre-commit',
  'chmod +x .hooks/pre-commit',
  'echo "✅ pre-commit hook установлен."',
]
