# SPDX-FileCopyrightText: 2025 RAprogramm <andrey.rozanov.vl@gmail.com>
#
# SPDX-License-Identifier: MIT

name: "Cargo fmt check"
description: "Run cargo fmt in check mode using the provided toolchain"
inputs:
  toolchain:
    description: "Rust toolchain identifier to use (without the leading +)"
    required: false
    default: "nightly"
runs:
  using: "composite"
  steps:
    - name: Run cargo fmt
      shell: bash
      env:
        TOOLCHAIN: ${{ inputs.toolchain }}
      run: |
        set -euo pipefail
        cargo +"${TOOLCHAIN}" fmt --all -- --check

