# SPDX-FileCopyrightText: 2025 RAprogramm <andrey.rozanov.vl@gmail.com>
#
# SPDX-License-Identifier: MIT

[patch.crates-io]
masterror-derive = { path = "masterror-derive" }
masterror-template = { path = "masterror-template" }
