# SPDX-FileCopyrightText: 2025 RAprogramm <andrey.rozanov.vl@gmail.com>
#
# SPDX-License-Identifier: MIT

name: Reusable CI

on:
  workflow_call:
    inputs:
      all-features:
        type: boolean
        default: true

jobs:
  validate-codecov-yaml:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5

      - name: Validate codecov.yml
        shell: bash
        run: |
          set -euo pipefail
          if [ ! -f .github/codecov.yml ]; then
            echo "codecov.yml not found, skipping validation"
            exit 0
          fi

          echo "Validating codecov.yml..."
          RESPONSE=$(cat .github/codecov.yml | curl -s --data-binary @- https://codecov.io/validate)

          if echo "$RESPONSE" | grep -q "^Valid!"; then
            echo "codecov.yml is valid"
            exit 0
          elif echo "$RESPONSE" | grep -q "^Error"; then
            echo "codecov.yml validation failed:"
            echo "$RESPONSE"
            exit 1
          else
            echo "Unexpected response from Codecov validator:"
            echo "$RESPONSE"
            exit 1
          fi

  msrv:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      version: ${{ steps.msrv.outputs.msrv }}
    steps:
      - uses: actions/checkout@v5

      - name: Read MSRV from Cargo.toml
        id: msrv
        shell: bash
        run: |
          set -euo pipefail
          if ! command -v jq >/dev/null 2>&1; then
            sudo apt-get update -y && sudo apt-get install -y jq
          fi
          RV=$(cargo metadata --no-deps --format-version=1 | jq -r '.packages[0].rust_version // empty')
          if [ -z "$RV" ]; then
            echo "rust-version is not set in Cargo.toml"
            exit 1
          fi
          [[ "$RV" =~ ^[0-9]+\.[0-9]+$ ]] && RV="${RV}.0"
          echo "msrv=${RV}" >> "$GITHUB_OUTPUT"
          echo "Using MSRV: $RV"

  fmt:
    runs-on: ubuntu-latest
    needs: msrv
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5

      - name: Install Rust (${{ needs.msrv.outputs.version }})
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ needs.msrv.outputs.version }}

      - name: Install nightly rustfmt
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt

      - name: Check formatting (nightly rustfmt)
        uses: ./.github/actions/cargo-fmt
        with:
          toolchain: nightly

  clippy:
    runs-on: ubuntu-latest
    needs: msrv
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        rust:
          - ${{ needs.msrv.outputs.version }}
          - stable
    steps:
      - uses: actions/checkout@v5

      - name: Install Rust (${{ matrix.rust }})
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          key: clippy-${{ matrix.rust }}
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Clippy (${{ matrix.rust }})
        uses: ./.github/actions/cargo-clippy
        with:
          toolchain: ${{ matrix.rust }}
          all-features: ${{ inputs.all-features }}

  deny:
    runs-on: ubuntu-latest
    needs: msrv
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5

      - name: Install Rust (${{ needs.msrv.outputs.version }})
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ needs.msrv.outputs.version }}

      - name: Cargo deny
        uses: ./.github/actions/cargo-deny

  audit:
    runs-on: ubuntu-latest
    needs: msrv
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5

      - name: Install Rust (${{ needs.msrv.outputs.version }})
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ needs.msrv.outputs.version }}

      - name: Security audit
        uses: ./.github/actions/cargo-audit

  test:
    runs-on: ubuntu-latest
    needs: [msrv, fmt, clippy]
    permissions:
      contents: write
      pull-requests: write
    strategy:
      fail-fast: false
      matrix:
        rust:
          - ${{ needs.msrv.outputs.version }}
          - stable
    env:
      CARGO_LOCKED: "true"
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Install Rust (${{ matrix.rust }})
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          key: test-${{ matrix.rust }}
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Install cargo-nextest
        if: matrix.rust == needs.msrv.outputs.version
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest

      - name: Verify lockfile is committed
        if: matrix.rust == needs.msrv.outputs.version
        shell: bash
        run: |
          set -euo pipefail
          if [ ! -f Cargo.lock ]; then
            echo "CARGO_LOCKED=1 but Cargo.lock is missing. Commit it or drop CARGO_LOCKED."
            exit 1
          fi

      - name: Build (may regenerate README to temp)
        if: matrix.rust == needs.msrv.outputs.version
        shell: bash
        env:
          TZ: UTC
          LC_ALL: C.UTF-8
          NO_COLOR: "1"
          CARGO_TERM_COLOR: never
          SOURCE_DATE_EPOCH: "0"
        run: |
          set -euo pipefail
          tmp="$(mktemp)"
          cargo +${{ matrix.rust }} build --workspace -q || cargo +${{ matrix.rust }} build -q
          if [ -f README.md ]; then
            cp -f README.md "$tmp"
            last_byte="$(tail -c1 "$tmp" 2>/dev/null || true)"
            if [ "${last_byte:-}" != $'\n' ]; then printf '\n' >> "$tmp"; fi
          else
            : > "$tmp"
          fi
          echo "README_CANDIDATE=$tmp" >> "$GITHUB_ENV"

      - name: README drift on PR (report only)
        if: github.event_name == 'pull_request' && matrix.rust == needs.msrv.outputs.version
        shell: bash
        run: |
          set -euo pipefail
          if [ ! -f README.md ]; then
            echo "README.md missing in repo; nothing to compare."
            exit 0
          fi
          if ! diff -u --label "README.md (HEAD)" --label "README.md (generated)" README.md "$README_CANDIDATE" >/tmp/readme.diff 2>/dev/null; then
            echo "::warning::README differs on PR. Tests proceed with HEAD, not rewriting the file."
            git --no-pager diff --no-index -- README.md "$README_CANDIDATE" || true
          else
            echo "README is up to date (PR)."
          fi

      - name: README autocommit on main (push or PR)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && matrix.rust == needs.msrv.outputs.version
        id: readme_update
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          need_update=0
          if [ ! -f README.md ]; then
            need_update=1
          elif ! cmp -s README.md "$README_CANDIDATE"; then
            need_update=1
          fi
          if [ "$need_update" -eq 0 ]; then
            echo "README is up to date (main)."
            echo "updated=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          echo "Updating README working tree..."
          cp -f "$README_CANDIDATE" README.md
          git add README.md

          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global --add safe.directory "$GITHUB_WORKSPACE"

          git commit -m "chore(readme): auto-refresh [skip ci]" || true

          set +e
          git pull --rebase --autostash origin main
          git push origin HEAD:main
          rc=$?
          set -e

          if [ $rc -eq 0 ]; then
            echo "Push to main succeeded."
            echo "updated=true" >> "$GITHUB_OUTPUT"
            git fetch origin main
            git reset --hard origin/main
            git clean -fdx
            exit 0
          fi

          echo "Push to main denied (likely branch protection). Preparing PR..."
          echo "updated=true" >> "$GITHUB_OUTPUT"
          BR="ci/readme-auto-refresh"
          git switch -c "$BR" || git checkout -b "$BR"
          git push -u origin "$BR" --force

          # Create or update PR using gh CLI
          if gh pr view "$BR" --json number >/dev/null 2>&1; then
            echo "PR already exists for $BR, updating..."
          else
            echo "Creating new PR for $BR..."
            gh pr create \
              --base main \
              --head "$BR" \
              --title "chore(readme): auto-refresh" \
              --body "Автоматически сгенерированный апдейт README. Прямой пуш в \`main\` запрещён политикой, поэтому открыт PR."
          fi

          # Enable auto-merge for README refresh PR
          echo "Enabling auto-merge for $BR..."
          gh pr merge --auto --squash --yes "$BR" || echo "Auto-merge already enabled or failed"

      - name: Tests with nextest (${{ matrix.rust }})
        if: matrix.rust == needs.msrv.outputs.version
        uses: ./.github/actions/cargo-test
        with:
          toolchain: ${{ matrix.rust }}
          all-features: ${{ inputs.all-features }}
          nextest-profile: ci

      - name: Tests (${{ matrix.rust }})
        if: matrix.rust != needs.msrv.outputs.version
        uses: ./.github/actions/cargo-test
        with:
          toolchain: ${{ matrix.rust }}
          all-features: ${{ inputs.all-features }}

      - name: Add test summary
        if: always() && matrix.rust == needs.msrv.outputs.version
        run: |
          echo "## Test Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- JUnit XML: \`target/nextest/ci/junit.xml\`" >> $GITHUB_STEP_SUMMARY
          echo "- Test results will be uploaded to Codecov Test Analytics in coverage job" >> $GITHUB_STEP_SUMMARY

      - name: Auto-commit README changes (any branch)
        if: always() && matrix.rust == needs.msrv.outputs.version
        run: |
          set -euo pipefail
          if ! cmp -s README.md "$README_CANDIDATE"; then
            echo "README changed, committing..."
            cp -f "$README_CANDIDATE" README.md
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --global --add safe.directory "$GITHUB_WORKSPACE"
            git add README.md
            git commit -m "chore(readme): auto-refresh [skip ci]" || true
          else
            echo "README already up to date."
          fi

  package:
    runs-on: ubuntu-latest
    needs: [msrv, test]
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5

      - name: Install Rust (${{ needs.msrv.outputs.version }})
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ needs.msrv.outputs.version }}

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Ensure tree is clean before package
        shell: bash
        run: |
          set -euo pipefail
          if ! git diff --quiet; then
            echo "Working tree is dirty:"
            git status --porcelain
            exit 1
          fi

      - name: Package (dry-run)
        run: cargo +${{ needs.msrv.outputs.version }} package --locked

  coverage:
    runs-on: ubuntu-latest
    needs: [test, validate-codecov-yaml]
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5

      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          components: llvm-tools-preview

      - name: Install cargo-llvm-cov and cargo-nextest
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-llvm-cov,cargo-nextest

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Generate coverage
        run: |
          cargo llvm-cov nextest --workspace --profile ci --all-features --lcov --output-path lcov.info
          cargo llvm-cov report --html

          # Extract coverage percentage for summary
          COVERAGE=$(cargo llvm-cov report | grep TOTAL | awk '{print $NF}')
          echo "COVERAGE_PCT=${COVERAGE}" >> $GITHUB_ENV

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: lcov.info
          fail_ci_if_error: false

      - name: Check JUnit XML exists
        id: check_junit
        if: always()
        shell: bash
        run: |
          if [ -f target/nextest/ci/junit.xml ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "JUnit XML found at target/nextest/ci/junit.xml"
          else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "Warning: JUnit XML not found at target/nextest/ci/junit.xml"
          fi

      - name: Upload test results to Codecov
        if: always() && steps.check_junit.outputs.exists == 'true'
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: target/nextest/ci/junit.xml
          fail_ci_if_error: false

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: target/llvm-cov/html/
          retention-days: 30

      - name: Upload test results artifact
        if: always() && steps.check_junit.outputs.exists == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/nextest/ci/junit.xml
          retention-days: 30

      - name: Add coverage summary
        run: |
          echo "## :shield: Coverage Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Metric | Value |" >> $GITHUB_STEP_SUMMARY
          echo "|--------|-------|" >> $GITHUB_STEP_SUMMARY
          echo "| **Total Coverage** | \`${COVERAGE_PCT}\` |" >> $GITHUB_STEP_SUMMARY
          echo "| **Target** | \`95%+\` |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "> :information_source: Full HTML report available in workflow artifacts (30 day retention)" >> $GITHUB_STEP_SUMMARY
          echo "> :test_tube: Test results (JUnit XML) uploaded to Codecov Test Analytics" >> $GITHUB_STEP_SUMMARY
          echo "> :chart_with_upwards_trend: [View on Codecov](https://app.codecov.io/gh/RAprogramm/masterror)" >> $GITHUB_STEP_SUMMARY

  benchmarks:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v5

      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Run benchmarks
        run: cargo bench --no-fail-fast --features benchmarks -- --save-baseline ci-baseline

      - name: Upload benchmark results
        uses: actions/upload-artifact@v4
        with:
          name: benchmark-results
          path: target/criterion/
          retention-days: 30

      - name: Download previous benchmark
        uses: actions/download-artifact@v4
        continue-on-error: true
        with:
          name: benchmark-results
          path: target/criterion-previous/

      - name: Compare with baseline
        continue-on-error: true
        run: |
          if [ -d "target/criterion-previous" ]; then
            echo "Comparing with previous benchmark..."
            cargo bench --features benchmarks -- --baseline ci-baseline --noplot
          else
            echo "No previous benchmark found, skipping comparison"
          fi

      - name: Add benchmark summary
        run: |
          echo "## Benchmark Results" >> $GITHUB_STEP_SUMMARY
          echo "Benchmark artifacts uploaded with 30-day retention:" >> $GITHUB_STEP_SUMMARY
          echo "- Criterion reports: \`target/criterion/\`" >> $GITHUB_STEP_SUMMARY
          echo "- Baseline: \`ci-baseline\`" >> $GITHUB_STEP_SUMMARY
