name: Translate README

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'README.md'
      - 'README.template.md'
      - '.github/workflows/translate-readme.yml'

permissions:
  contents: write
  models: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  translate:
    runs-on: ubuntu-latest
    # Skip if commit is from bot (prevent loops)
    if: "!contains(github.event.head_commit.message, '[cai]') && github.actor != 'genaiscript'"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache GenAIScript translations
        uses: actions/cache@v4
        with:
          path: .genaiscript/cache/**
          key: continuous-translation-${{ github.run_id }}
          restore-keys: |
            continuous-translation-

      - name: Translate to Russian and Korean
        uses: pelikhan/action-continuous-translation@v0
        continue-on-error: true
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          lang: ru,ko
          files: README.md
          source: en
          max_translation_tokens: 8000
          max_validation_tokens: 2000

      - name: Commit translations
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          file_pattern: '**.md* translations/**'
          commit_message: '[cai] 🤖 auto-translate README to Russian and Korean'
          commit_user_name: 'genaiscript'
          commit_user_email: '41898282+github-actions[bot]@users.noreply.github.com'
