name: Translate README

on:
  push:
    branches:
      - main
    paths:
      - 'README.md'
      - 'README.template.md'
      - '.github/workflows/translate-readme.yml'
  workflow_dispatch:

permissions:
  contents: write
  models: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  translate:
    runs-on: ubuntu-latest
    # Skip if commit is from bot (prevent loops)
    if: "!contains(github.event.head_commit.message, '[skip ci]') && github.actor != 'github-actions[bot]'"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.CLASSIC }}

      - name: Cache GenAIScript translations
        uses: actions/cache@v4
        with:
          path: .genaiscript/cache/**
          key: genaiscript-${{ github.run_id }}
          restore-keys: |
            genaiscript-

      - name: Translate to Russian
        uses: pelikhan/action-continuous-translation@v0
        with:
          github_token: ${{ secrets.CLASSIC }}
          lang: ru
          files: README.md
          source: en
          max_translation_tokens: 8000
          max_validation_tokens: 2000
          filename_template: "{{dirname}}/{{basename}}.{{lang}}{{extname}}"

      - name: Translate to Chinese
        uses: pelikhan/action-continuous-translation@v0
        with:
          github_token: ${{ secrets.CLASSIC }}
          lang: zh-CN
          files: README.md
          source: en
          max_translation_tokens: 8000
          max_validation_tokens: 2000
          filename_template: "{{dirname}}/{{basename}}.{{lang}}{{extname}}"

      - name: Commit translations
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          if git diff --quiet README.ru.md README.zh-CN.md; then
            echo "No translation changes detected"
            exit 0
          fi

          git add README.ru.md README.zh-CN.md
          git commit -m "chore: auto-translate README [skip ci]

Automated AI translation via action-continuous-translation.

Translations updated at $(date -u +'%Y-%m-%d %H:%M UTC')
Source: README.md (English)
Targets: Russian, Chinese (Simplified)"

          git pull --rebase origin main
          git push origin main
